### ISSUE TITLE
License check breaks usage with vdom admin

### ISSUE THREAD

**Issue by jweiher** [fortinet-solutions-cse/fortiosapi#47] opened 2019-07-05 07:49 UTC
Hi,

because the library is trying to access the global vdom here:
https://github.com/fortinet-solutions-cse/fortiosapi/blob/a72b5434491c049c82336c85be5afe7092660a86/fortiosapi/fortiosapi.py#L180

it is not possible to use it with an administrator inside a vdom, because this user obviously cant access the global vdom.

To be honest - I'm not quite sure why this is required anyways?

For the sake of completeness - this is the error which is thrown:
```
  File "[...]site-packages/fortiosapi/fortiosapi.py", line 182, in login
    self._fortiversion = resp_lic['version']
TypeError: 'Response' object is not subscriptable
```

To reproduce:
1. Create VDOM
2. Create Administrator for this vdom
3. Try to use the library with the vdom's IP and the created admin user

I'm using a 60d with 5.6.9.

regards,
Jan

**Comment by kifeo** [comment] 2019-07-10 09:55
I went into this issue also with Fortigate 60E 6.0.5

**Comment by kifeo** [comment] 2019-07-10 13:06
httpsd debugs : 

> [httpsd 7151 - 1562763753 warning] api_access_check_for_api_key[962] -- API Key request authorized for <removed_username> from <removed_ip>.
> [httpsd 7151 - 1562763753 info] api_store_parameter[227] -- add API parameter 'global': '"1"' (type=string)
> [httpsd 7151 - 1562763753 info] api_parse_vdom_list[972] -- request is for all VDOMs
> [httpsd 7151 - 1562763753 info] endpoint_process_req_vdom[452] -- new API request (action='select',path='license',name='status',vdom='root',user='homeassistant')
> [httpsd 7151 - 1562763753 error] api_return_http_result[631] -- API error 403 raised

**Comment by Grisha-L** [comment] 2019-07-22 15:21
Same here, using FGVM 6.0.4.

The issue is that the REST API account can't be assigned to the "Global" VDOM, therefor the account will never have the required permissions to look for the license state when VDOMs are enabled.

I agree with **jweiher** and think that the license check isn't required at all, it can be added as a side function in case required without forcing for such check on every connect.

Regards,

**Comment by thomnico** [comment] 2019-07-22 15:42
Hello all,

I agree this should be moved out of the way here. Meanwhile it is an important for usability to know that errors are due to License.

**Comment by thomnico** [comment] 2019-07-22 15:43
I will pushed an update version (including tests) this week

**Closed** 2019-07-24 08:30 UTC
