### ISSUE TITLE
Disable SSL verification not working in 1.0.1

### ISSUE THREAD

**Issue by refriedjello** [fortinet-solutions-cse/fortiosapi#51] opened 2019-08-19 19:32 UTC
FortiOS API: 1.0.1
Python: 2.7.5
Ansible: 2.8.2
Ansible Module: fortios
OS: CentOS 7.6.1810

I was not able to connect to a lab FortiGate running 5.6.8 and a self-signed certificate due to this error:

> fatal: [localhost -> localhost]: FAILED! => {"changed": false, "module_stderr": "No handlers could be found for logger \"fortiosapi\"\nTraceback (most recent call last):\n  File \"/home/user.name/.ansible/tmp/ansible-tmp-1566238292.13-228453108213076/AnsiballZ_fortios_system_accprofile.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/home/user.name/.ansible/tmp/ansible-tmp-1566238292.13-228453108213076/AnsiballZ_fortios_system_accprofile.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/user.name/.ansible/tmp/ansible-tmp-1566238292.13-228453108213076/AnsiballZ_fortios_system_accprofile.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_fortios_system_accprofile_payload_nhat_l/__main__.py\", line 730, in <module>\n  File \"/tmp/ansible_fortios_system_accprofile_payload_nhat_l/__main__.py\", line 721, in main\n  File \"/tmp/ansible_fortios_system_accprofile_payload_nhat_l/__main__.py\", line 584, in fortios_system\n  File \"/tmp/ansible_fortios_system_accprofile_payload_nhat_l/__main__.py\", line 530, in login\n  File \"/usr/lib/python2.7/site-packages/fortiosapi/fortiosapi.py\", line 170, in login\n    data='username=' + urllib.parse.quote(username) + '&secretkey=' + urllib.parse.quote(password) + \"&ajax=1\", timeout=self.timeout)\n  File \"/usr/lib/python2.7/site-packages/requests/sessions.py\", line 555, in post\n    return self.request('POST', url, data=data, json=json, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/requests/sessions.py\", line 508, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/lib/python2.7/site-packages/requests/sessions.py\", line 618, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/requests/adapters.py\", line 506, in send\n    raise SSLError(e, request=request)\nrequests.exceptions.SSLError: HTTPSConnectionPool(host='labfirewall.domain.com', port=443): Max retries exceeded with url: /logincheck (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)'),))\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

I played around with the fortiosapi.py script a bit trying to override that, but ultimately the only way I found that works was to:

1) Open file fortiosapi.py
E.g. : /usr/lib/python2.7/site-packages/fortiosapi/fortiosapi.py

2) Go to line 171 :

`            data='username=' + urllib.parse.quote(username) + '&secretkey=' + urllib.parse.quote(password) + "&ajax=1", timeout=self.timeout)`

3) Add ", verify=False" to the end of those parameters :

`            data='username=' + urllib.parse.quote(username) + '&secretkey=' + urllib.parse.quote(password) + "&ajax=1", timeout=self.timeout, verify=False)`

4) Test playbook

It appears two things are true:

1) Overriding "verify = " earlier in the script does not work as it should
2) There is no ability to specify to ignore cert errors or not, via a playbook.

**Comment by sbraz** [comment] 2019-08-22 12:59
The problem is that the  default value of `verify` was changed for `login` functions, see https://github.com/fortinet-solutions-cse/fortiosapi/compare/026ab3b777c378713081cf237a95d6b781cb20cf...v1.0.1

You only need to change the default value of `verify` in those function definitions if you want the plugin to work with ansible.

**Comment by sbraz** [comment] 2019-08-22 13:10
Apparently the latest version of the ansible module (not yet pushed to the ansible repo) adds a parameter to disable certificate verification: https://github.com/fortinet-solutions-cse/ansible_fgt_modules/commit/7cc5be875a5ff44f196ec42b4c26181020019d26

@mamunozgonzalez I think that in order to avoid breaking existing systems, a new version of the PyPI module should be released without certificate verification and the change should be re-added *only* when the `ssl_verify` option has ben added to a new Ansible release.

**Comment by mamunozgonzalez** [comment] 2019-08-22 14:12
Hi @sbraz 
thanks for your comments. Yes, fortiosapi now sets verify to True by default. We know it is a non-backward compatible change and that's why fortiosapi changed major version (1.0.x).

This change was done with security in mind. We know the systems will have to be adapted but it is a must to have security enabled by default. Actually what we had until now (verify = false) was a temporary and exceptional behaviour.

**Comment by sbraz** [comment] 2019-08-22 14:56
@mamunozgonzalez I understand that is a non-backwards-compatible change but at the moment there is no way at all to keep using Ansible's FortiOS modules if we have a self-signed certificate.

I think this shouldn't have been done before having the `ssl_verify` available through "normal" Ansible packages. For instance we use Ansible with AWX so there is no easy way for us to install "ansible_fgt_modules" (at least not that I know of).

**Comment by mamunozgonzalez** [comment] 2019-08-22 16:51
Hi @sbraz,
  I see your point. Please let me show you different options:

- The new Ansible modules supporting this and other new features and updates required by Ansible have been already committed and approved (most of them) and will be ready in 2.9 (code freeze is next week, 28th August). They are now available in devel branch of Ansible distribution already in case you want to have a look. Please note that they come with a lot of changes that were mandatory and unavoidable due to Ansible natural evolution, such as changing the name of attributes to avoid hyphens and use underscores instead. This and other changes will be non backward compatible in your playbooks.

- In case you want to use the modules from our ansible_fgt_modules repo you can instruct Ansible Tower to point to a different library. Can you try modifying /etc/ansible/ansible.cfg? as indicated here: https://access.redhat.com/solutions/3060221 (please note we don't support directly Ansible Tower as it is a RedHat product). I have just asked some good colleagues from RedHat to double check this point, just in case.

- You can also use a previous fortiosapi version with pip if it works fine with your environment.

- You can also modify locally your fortiosapi file to revert the change. You have to modify the login method. I can assist you with that if needed.

Please let me know if any of these options works for you. I can help you with some of them (ultimately we can setup a support session via your Fortinet Sales representative if needed)

**Comment by sbraz** [comment] 2019-08-22 17:15
Thanks for your detailed answer!

I didn't notice that the new version had been merged into ansible already, I was looking at the wrong files earlier when I said that this hadn't been added in ansible's repo.

Until v2.9 is out, I will probably keep using an older PyPI version, since it's the easiest solution.

Anyway this is nothing critical for us as we can easily patch the file, use an older version (or even install the newest library version into AWX even if it means more work).

I was just slightly upset that Fortinet didn't wait until the new ansible version was released (and the doc on updated to reflect the existence of an option to disable certificate verification) before bumping the API. Breaking changes can happen but it's always easier when the software that depends on your library is able to work with the latest version.

**Comment by mamunozgonzalez** [comment] 2019-08-23 07:57
Sounds good. I agree your selected choice is probably the most optimal one.

And thanks for your feedback, it's very valuable and we totally understand your point: Next time we will have more flexibility to work with updates in Ansible since all the "Ansible Core Network" is moving out and being packed in a new thing named "collections" that will be handled separately, thus avoiding the limitations of Ansible releases.

**Closed** 2019-08-23 07:58 UTC

**Comment by davehouser1** [comment] 2020-02-06 02:08
FortiOS API: 1.0.1
Python: 2.7.17
Ansible: 2.9.4
Ansible Module: fortios_user_ldap
Ubuntu 18.04

I am having a similar issue, I don't believe I fully understand the solution posted here. I still get certificate errors even when trying to use ssl_verify: "False". Are there any other solutions? What version of fortiosapi do I need to use to get this to work? Are there any plans to support Python3?

**Comment by greenspartan** [comment] 2020-04-07 14:04
Hi,

I confirm it doesn't work for me neither using ssl_verify: "False" in my playbook.
You can find error message attached.
[job_203.txt](https://github.com/fortinet-solutions-cse/fortiosapi/files/4444845/job_203.txt)

My env is:
Ansible: 2.9.6
Python 2.7.17
FortiosAPI: 1.0.1
Ansible module : fortios_firewall_adress

I have tried also to modify fortiosapi.py on line 171 and put  ", verify=False" as advised above but it didn't help.

Thanks for your help ;)

Adrien

**Comment by thomnico** [comment] 2020-04-07 15:31
Hello @greenspartan  this issue has been closed and discussed for a while. 

Can you provide a fortiosapi example (in python) which does not work ? Or more likely check the different discussion on solving for Ansible which is not managed here.

**Comment by rdzielicki** [comment] 2020-04-07 15:57
Hello,

No it's related to FortiOS libs, tried virtualenv with Ansible 2.8.X and Ansible 2.9, Python 2 & 3:

"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\\n  InsecureRequestWarning,\\nTraceback (most recent call last):\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1586274310.5238984-83337164666689/AnsiballZ_fortios_firewall_address.py\\", line 102, in <module>\\n    _ansiballz_main()\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1586274310.5238984-83337164666689/AnsiballZ_fortios_firewall_address.py\\", line 94, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1586274310.5238984-83337164666689/AnsiballZ_fortios_firewall_address.py\\", line 40, in invoke_module\\n    runpy.run_module(mod_name='ansible.modules.network.fortios.fortios_firewall_address', init_globals=None, run_name='__main__', alter_sys=True)\\n  File \\"/usr/lib64/python3.6/runpy.py\\", line 205, in run_module\\n    return _run_module_code(code, init_globals, run_name, mod_spec)\\n  File \\"/usr/lib64/python3.6/runpy.py\\", line 96, in _run_module_code\\n    mod_name, mod_spec, pkg_name, script_name)\\n  File \\"/usr/lib64/python3.6/runpy.py\\", line 85, in _run_code\\n    exec(code, run_globals)\\n  File \\"/tmp/ansible_fortios_firewall_address_payload_sjiczztu/ansible_fortios_firewall_address_payload.zip/ansible/modules/network/fortios/fortios_firewall_address.py\\", line 570, in <module>\\n  File \\"/tmp/ansible_fortios_firewall_address_payload_sjiczztu/ansible_fortios_firewall_address_payload.zip/ansible/modules/network/fortios/fortios_firewall_address.py\\", line 560, in main\\n  File \\"/tmp/ansible_fortios_firewall_address_payload_sjiczztu/ansible_fortios_firewall_address_payload.zip/ansible/modules/network/fortios/fortios_firewall_address.py\\", line 462, in fortios_firewall\\n  File \\"/tmp/ansible_fortios_firewall_address_payload_sjiczztu/ansible_fortios_firewall_address_payload.zip/ansible/modules/network/fortios/fortios_firewall_address.py\\", line 445, in firewall_address\\n  File \\"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi.py\\", line 417, in set\\n    mkey = self.get_mkey(path, name, data, vdom=vdom)\\n  File \\"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi.py\\", line 228, in get_mkey\\n    keyname = self.get_mkeyname(path, name, vdom)\\n  File \\"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi.py\\", line 217, in get_mkeyname\\n    schema = self.schema(path, name, vdom=vdom)\\n  File \\"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi.py\\", line 317, in schema\\n    url = self.cmdb_url(path, name, vdom=vdom) + \\"&action=schema\\"\\n  File \\"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi.py\\", line 252, in cmdb_url\\n    self.check_session()\\n  File \\"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi.py\\", line 126, in check_session\\n    raise NotLogged()\\nfortiosapi.exceptions.NotLogged: Not logged on a session, please login.\\n",

We have already edit fortiosapi.py to set verify to false

**Comment by thomnico** [comment] 2020-04-07 17:12
I explicitely ask a simple example without Ansible. There is no instruction to reproduce in there

**Comment by greenspartan** [comment] 2020-04-08 05:25
Hello,

Indeed we are using fortios_firewall_adress module in an Ansible playbook, that relies on fortiosapi.py.
That's why I thought appropriate to post here as error message related to SSL.
If this thread is not the appropriate, we will create a new thread on Ansible/Issues section.

As rdzielicki said, we tried various Ansible version from 2.8 to 2.9.6 and various Python version.
We ended with same SSL error message.
Ansible is running via Tower 3.6.3 on Centos server using following playbook:

`---                                                                               
                                                                                  
- hosts: localhost
  gather_facts: False
  vars:                                                                           
   host: "1.2.3.4"                                                           
   username: "administrator"                                                              
   password: "toto"                                                          
   vdom: "root"                                                            
  tasks:                                                                          
  - name: Configure IPv4 addresses.                                               
    fortios_firewall_address:                                                     
      host:  "{{ host }}"                                                         
      username: "{{ username }}"                                                  
      password: "{{ password }}"                                                  
      vdom:  "root"                                                         
      state: "present"                                                            
      firewall_address:                                                           
        name: "TEST_OBJECT"                                                
        subnet: "5.5.5.5 255.255.255.255" `

Fortigate firewall is 240D running on 6.0.6

Don't hesitate to let us know if this is not the appropriate place to post.
